# Generated by Django 4.0.4 on 2022-06-14 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploadTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('userKey', models.CharField(default='1234', max_length=100, primary_key=True, serialize=False)),
                ('pubAddress', models.CharField(default='0x0.61899174195931960.011398521152146568', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('index', models.IntegerField(default=0)),
                ('TypeOfData', models.CharField(blank=True, max_length=100, null=True)),
                ('IpfsHash', models.CharField(default='', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('TimeStamp', models.DateTimeField(blank=True, null=True, unique=True)),
                ('UploadTnxHash', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ethereumWeb3App.user')),
            ],
        ),
    ]
