# Generated by Django 4.0.4 on 2022-06-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethereumWeb3App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pubAddress',
            field=models.CharField(default='0x0.90163265383756070.735822005272582', max_length=100),
        ),
    ]
