# Generated by Django 4.0.4 on 2022-06-03 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethereumWeb3App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('documents', models.FileField(upload_to='documents/')),
                ('uploadTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
