# Generated by Django 4.0.4 on 2022-06-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethereumWeb3App', '0002_alter_user_pubaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pubAddress',
            field=models.CharField(default='0x', max_length=100),
        ),
    ]
