# Generated by Django 4.0.4 on 2022-06-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethereumWeb3App', '0003_alter_user_pubaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='IpfsUrl',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
