# Generated by Django 4.0.4 on 2022-06-15 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethereumWeb3App', '0003_alter_user_pubaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccIndex',
            fields=[
                ('index', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
