# Generated by Django 4.0.4 on 2022-06-15 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ethereumWeb3App', '0004_accindex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accindex',
            old_name='index',
            new_name='AccIndex',
        ),
    ]
