# Generated by Django 4.0.4 on 2022-06-15 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ethereumWeb3App', '0005_rename_index_accindex_accindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='accindex',
            name='userKey',
            field=models.ForeignKey(default='a24fc86b', on_delete=django.db.models.deletion.CASCADE, to='ethereumWeb3App.user'),
        ),
    ]
