# Generated by Django 4.0.4 on 2022-06-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethereumWeb3App', '0005_userdata_assetname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='TimeStamp',
            field=models.DateTimeField(auto_now_add=True, null=True, unique=True),
        ),
    ]
