# Generated by Django 4.0.4 on 2022-06-15 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ethereumWeb3App', '0006_accindex_userkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accindex',
            name='userKey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ethereumWeb3App.user'),
        ),
    ]
