# Generated by Django 4.0.4 on 2022-06-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethereumWeb3App', '0007_alter_userdata_uploadtnxhash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='UploadTnxHash',
            field=models.CharField(blank=True, default='123', max_length=100, null=True),
        ),
    ]
