# Generated by Django 4.0.4 on 2022-06-25 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethereumWeb3App', '0008_alter_userdata_uploadtnxhash'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
